run:
  timeout: 5m
  issues-exit-code: 1

linter-settings:
  errcheck: 
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  staticcheck:
    checks: ["all"]
  gocyclo:
    min-complexity: 10

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gocycle
    - gofmt
    - goimports
    - ineffassign
    - deadcode
    - unused
    - structcheckuk

excude-dirs:
  - vendor
  - third-party
  - .git

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - errcheck